import React, { useState, useEffect, useCallback } from "react";
import ProductCard from "../components/ProductCard";
import ImageGallery from "../components/ImageGallery";
import ConfidenceTable from "../components/ConfidenceTable";
import ReviewActions from "../components/ReviewActions";
import { COLORS, fontStack, monoStack, Icons, formatDate } from "../components/Layout";
import { fetchReviewQueue, DEFAULT_REVIEW_QUEUE_URL, AUTO_REFRESH_MS } from "../utils/pipelineFolderParser";

function ConnectionCard({ onConnect, error, loading }) {
  const [url, setUrl] = useState(DEFAULT_REVIEW_QUEUE_URL);

  return (
    <div style={{ fontFamily: fontStack }}>
      <div style={{ background: COLORS.white, borderRadius: 16, border: `1px solid ${COLORS.g200}`, padding: 28 }}>
        <div style={{ marginBottom: 22 }}>
          <div style={{ fontSize: 18, fontWeight: 800, color: COLORS.g900, marginBottom: 8 }}>Load Pipeline Review Queue</div>
          <div style={{ fontSize: 13, color: COLORS.g500, lineHeight: 1.7 }}>
            Connect to the pipeline's <strong>review_queue.json</strong> to begin reviewing product image matches.
            The review queue is generated by the demo pipeline after scraping, classifying, and ranking candidate images.
          </div>
        </div>

        <div style={{ marginBottom: 16 }}>
          <label style={{ fontSize: 12, fontWeight: 600, color: COLORS.g600, display: "block", marginBottom: 6 }}>
            Review Queue URL
          </label>
          <input
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            placeholder={DEFAULT_REVIEW_QUEUE_URL}
            style={{
              width: "100%", padding: "10px 14px", borderRadius: 8,
              border: `1px solid ${COLORS.g200}`, fontSize: 13,
              fontFamily: fontStack, outline: "none", boxSizing: "border-box",
            }}
          />
        </div>

        <button
          onClick={() => onConnect(url)}
          disabled={loading}
          style={{
            background: COLORS.blue, color: "#fff", border: "none",
            borderRadius: 14, padding: "18px 16px", fontSize: 14,
            fontWeight: 800, cursor: loading ? "default" : "pointer",
            fontFamily: fontStack, textAlign: "left", width: "100%",
            opacity: loading ? 0.7 : 1,
          }}
        >
          <div style={{ marginBottom: 6 }}>{loading ? "Loading..." : "Load Review Queue"}</div>
          <div style={{ fontSize: 12, fontWeight: 500, lineHeight: 1.5, opacity: 0.92 }}>
            Fetches the pre-built review queue and refreshes automatically every 15 seconds.
          </div>
        </button>

        {error && <div style={{ marginTop: 16, color: COLORS.red, fontSize: 13 }}>{error}</div>}
      </div>
    </div>
  );
}

export default function ReviewPage({ queue, onLoadPipelineData, onSubmitReview }) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [selectedImageIdx, setSelectedImageIdx] = useState(0);
  const [connection, setConnection] = useState(null);
  const [syncing, setSyncing] = useState(false);
  const [syncError, setSyncError] = useState(null);
  const [autoRefresh, setAutoRefresh] = useState(true);
  const [lastSyncedAt, setLastSyncedAt] = useState(null);
  const [lastScanProductCount, setLastScanProductCount] = useState(0);

  const connectedUrlRef = React.useRef(null);

  const product = queue[currentIndex] || queue[0];
  const images = product?.candidateImages || [];
  const hasImages = images.length > 0;

  useEffect(() => {
    if (queue.length === 0) {
      setCurrentIndex(0);
      setSelectedImageIdx(0);
      return;
    }
    if (currentIndex > queue.length - 1) setCurrentIndex(queue.length - 1);
    if (selectedImageIdx > (queue[Math.min(currentIndex, queue.length - 1)]?.candidateImages?.length || 1) - 1) setSelectedImageIdx(0);
  }, [queue, currentIndex, selectedImageIdx]);

  const refreshQueue = useCallback(async () => {
    if (!connectedUrlRef.current) return;
    setSyncing(true);
    try {
      const products = await fetchReviewQueue(connectedUrlRef.current);
      onLoadPipelineData(products);
      setLastScanProductCount(products.length);
      setLastSyncedAt(new Date().toISOString());
      setSyncError(null);
    } catch (err) {
      setSyncError(err.message || "Failed to load review queue.");
    } finally {
      setSyncing(false);
    }
  }, [onLoadPipelineData]);

  const handleConnect = useCallback(async (url) => {
    connectedUrlRef.current = url || DEFAULT_REVIEW_QUEUE_URL;
    setConnection({ label: connectedUrlRef.current });
    setCurrentIndex(0);
    setSelectedImageIdx(0);
    await refreshQueue();
  }, [refreshQueue]);

  useEffect(() => {
    if (!connection || !autoRefresh) return undefined;
    const timer = window.setInterval(refreshQueue, AUTO_REFRESH_MS);
    return () => window.clearInterval(timer);
  }, [connection, autoRefresh, refreshQueue]);

  useEffect(() => {
    const handler = (event) => {
      const tag = event.target.tagName;
      if (tag === "INPUT" || tag === "TEXTAREA") return;
      if (event.key === "ArrowRight" && hasImages) setSelectedImageIdx((index) => Math.min(index + 1, images.length - 1));
      if (event.key === "ArrowLeft" && hasImages) setSelectedImageIdx((index) => Math.max(index - 1, 0));
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [images.length, hasImages]);

  const handleSubmit = useCallback((reviewData) => {
    if (!product) return;
    onSubmitReview({ queueKey: product.queueKey, itemNumber: product.itemNumber, ...reviewData, selectedImageId: images[selectedImageIdx]?.id });
    setSelectedImageIdx(0);
  }, [product, images, selectedImageIdx, onSubmitReview]);

  const disconnectSource = useCallback(() => {
    connectedUrlRef.current = null;
    setConnection(null);
    setCurrentIndex(0);
    setSelectedImageIdx(0);
    setLastSyncedAt(null);
    setLastScanProductCount(0);
    setSyncError(null);
    onLoadPipelineData([]);
  }, [onLoadPipelineData]);

  if (!connection) {
    return <ConnectionCard onConnect={handleConnect} error={syncError} loading={syncing} />;
  }

  if (queue.length === 0) {
    return (
      <div style={{ fontFamily: fontStack }}>
        <div style={{ background: COLORS.white, borderRadius: 16, border: `1px solid ${COLORS.g200}`, padding: 24, marginBottom: 20 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" }}>
            <div>
              <div style={{ fontSize: 18, fontWeight: 800, color: COLORS.g900, marginBottom: 6 }}>Pipeline Review Queue</div>
              <div style={{ fontSize: 13, color: COLORS.g500, lineHeight: 1.6 }}>
                Source: <strong>{connection.label}</strong>
                {lastSyncedAt && <> · Last synced {formatDate(lastSyncedAt)}</>}
                {lastScanProductCount > 0 && <> · {lastScanProductCount} products loaded</>}
              </div>
            </div>
            <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
              <button onClick={refreshQueue} style={{ background: COLORS.blue, color: "#fff", border: "none", borderRadius: 10, padding: "10px 16px", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: fontStack }}>
                {syncing ? "Refreshing..." : "Refresh Now"}
              </button>
              <button onClick={disconnectSource} style={{ background: COLORS.g100, color: COLORS.g700, border: `1px solid ${COLORS.g300}`, borderRadius: 10, padding: "10px 16px", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: fontStack }}>
                Disconnect
              </button>
            </div>
          </div>
        </div>

        <div style={{ background: COLORS.white, borderRadius: 16, border: `1px solid ${COLORS.g200}`, padding: "64px 24px", textAlign: "center" }}>
          <div style={{ fontSize: 22, fontWeight: 800, color: COLORS.g900, marginBottom: 10 }}>
            {syncing ? "Loading review queue..." : "No pending products right now"}
          </div>
          <div style={{ fontSize: 14, color: COLORS.g500, lineHeight: 1.7, maxWidth: 680, margin: "0 auto" }}>
            The page is connected and re-checks the review queue every 15 seconds.
            Already-reviewed products are excluded from the queue for this session.
          </div>
          <label style={{ marginTop: 18, display: "inline-flex", alignItems: "center", gap: 8, fontSize: 13, color: COLORS.g600 }}>
            <input type="checkbox" checked={autoRefresh} onChange={(event) => setAutoRefresh(event.target.checked)} />
            Auto-refresh every 15 seconds
          </label>
          {syncError && <div style={{ marginTop: 16, color: COLORS.red, fontSize: 13 }}>{syncError}</div>}
        </div>
      </div>
    );
  }

  return (
    <div style={{ fontFamily: fontStack }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16, gap: 12, flexWrap: "wrap" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", justifyContent: "flex-end" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 12, color: COLORS.g400 }}>
            <Icons.Table />
            <span style={{ fontFamily: monoStack }}>{connection.label}</span>
            {lastSyncedAt && <span>· {formatDate(lastSyncedAt)}</span>}
          </div>
          <label style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 12, color: COLORS.g500 }}>
            <input type="checkbox" checked={autoRefresh} onChange={(event) => setAutoRefresh(event.target.checked)} />
            Auto-refresh
          </label>
          <button onClick={refreshQueue} style={{ background: COLORS.white, color: COLORS.blue, border: `1px solid ${COLORS.blue}`, borderRadius: 8, padding: "8px 12px", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: fontStack }}>
            {syncing ? "Refreshing..." : "Refresh"}
          </button>
          <button onClick={disconnectSource} style={{ background: COLORS.g100, color: COLORS.g700, border: `1px solid ${COLORS.g300}`, borderRadius: 8, padding: "8px 12px", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: fontStack }}>
            Disconnect
          </button>
        </div>
      </div>
      {syncError && <div style={{ marginBottom: 16, color: COLORS.red, fontSize: 13 }}>{syncError}</div>}

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 24, marginBottom: 24 }}>
        <ProductCard product={product} />
        {hasImages ? (
          <ImageGallery images={images} selectedIndex={selectedImageIdx} onSelectImage={setSelectedImageIdx} />
        ) : (
          <div style={{ background: COLORS.amberBg, border: `1px solid ${COLORS.amberBorder}`, borderRadius: 12, padding: "40px 24px", textAlign: "center", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
            <div style={{ fontSize: 14, fontWeight: 600, color: COLORS.amber, marginBottom: 6 }}>No candidate images for this product</div>
            <div style={{ fontSize: 12, color: COLORS.g500 }}>The pipeline did not produce any ranked images for this product.</div>
          </div>
        )}
      </div>

      {hasImages && (
        <div style={{ marginBottom: 24 }}>
          <ConfidenceTable images={images} selectedIndex={selectedImageIdx} onSelectImage={setSelectedImageIdx} />
        </div>
      )}

      {hasImages ? (
        <ReviewActions onSubmit={handleSubmit} onNextBestImage={() => setSelectedImageIdx((index) => Math.min(index + 1, images.length - 1))} canGoNext={selectedImageIdx < images.length - 1} />
      ) : (
        <div style={{ background: COLORS.white, borderRadius: 12, border: `1px solid ${COLORS.g200}`, padding: 20, display: "flex", gap: 12 }}>
          <button onClick={() => handleSubmit({ decision: "skipped", feedback: "No candidate images available", feedbackTags: [] })} style={{ background: COLORS.g100, color: COLORS.g600, border: `1px solid ${COLORS.g300}`, borderRadius: 10, padding: "12px 24px", fontSize: 15, fontWeight: 600, cursor: "pointer", display: "flex", alignItems: "center", gap: 8, fontFamily: fontStack }}>
            <Icons.Skip /> Skip — No Images
          </button>
        </div>
      )}
    </div>
  );
}
